### ISSUE TITLE
READ Users

### ISSUE THREAD

**Issue by sbvanyo** [sbvanyo/rare-server#15]

**Comment by DavidBPoole** [comment]
Create function to view all users.

Should see a list of users containing the username, first name, last name, and email of each user and the list should be ordered by username.

**Comment by DavidBPoole** [comment]
Create function to view a single user.

Given a user is on the post detail page or user list page
When they click on the user's name
Then they should be routed to that user's detail page including:

Full name
Profile image (if it exists)
Username
Creation Date
Bio

**Comment by DavidBPoole** [comment]
Should see a list of users containing the username, first name, last name, and email of each user and the list should be ordered by username.

**Comment by DavidBPoole** [comment]
User Model:

id   int
first_name   varchar
last_name   varchar
email   varchar
bio   varchar
username   varchar
password   varchar
profile_image_url   varchar
created_on   date
active   boolean

**Comment by DavidBPoole** [comment]
Function to view all users or single users completed.
