### ISSUE TITLE
UPDATE Users

### ISSUE THREAD

**Issue by sbvanyo** [sbvanyo/rare-server#16]

**Comment by DavidBPoole** [comment]
Create function to update user information.

**Comment by DavidBPoole** [comment]
Running into a problem with updating a user. Testing in postman when the request is ran it simply hangs and never completes with message "Sending request...". All other commands to GET and CREATE a user work despite UPDATE not working. Code has been checked and will require additional help.

**Comment by DavidBPoole** [comment]
Call is functioning correctly as of Nov 4.
